default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: 12345

development:
  <<: *default
  database: /Users/anton/pg_data

test: &test
  <<: *default
  database: /Users/anton/pg_data
